# Generated by Django 4.1.4 on 2023-01-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
    ]
