# Generated by Django 4.1.4 on 2023-01-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, max_length=20, upload_to='images/'),
        ),
    ]
