# Generated by Django 4.1.4 on 2023-01-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
